#######################################################
# 
# Mapa.py
# Python implementation of the Class Mapa
# Generated by Enterprise Architect
# Created on:      27-maj-2026 15:33:37
# Original author: s33314
# 
#######################################################
from Struktura.Zgloszenie import Zgloszenie

class Mapa:
    m_Zgloszenie= Zgloszenie()

    def filtruj():
        pass

    def zaktualizujWidokMapy():
        pass